# Generated by Django 5.1.6 on 2025-04-23 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_management', '0002_transfer_contact_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='working_hours_ar',
            field=models.TextField(blank=True, help_text='Business hours information in Arabic', verbose_name='Working Hours (Arabic)'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='working_hours_en',
            field=models.TextField(blank=True, help_text='Business hours information in English', verbose_name='Working Hours (English)'),
        ),
    ]
