# Generated by Django 5.1.6 on 2025-04-11 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_cover_image_project_is_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='client',
        ),
        migrations.AddField(
            model_name='project',
            name='client_ar',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='client_en',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
