# Generated by Django 5.2 on 2025-04-12 13:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_en', models.CharField(max_length=100)),
                ('name_ar', models.CharField(blank=True, max_length=100)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description_en', models.TextField(blank=True)),
                ('description_ar', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text="Icon name from icon library (e.g., 'home')", max_length=100)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of appearance in listing')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Service Category',
                'verbose_name_plural': 'Service Categories',
                'ordering': ['order', 'name_en'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title_en', models.CharField(max_length=200)),
                ('title_ar', models.CharField(blank=True, max_length=200)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('description_en', models.TextField()),
                ('description_ar', models.TextField(blank=True)),
                ('short_description_en', models.CharField(blank=True, max_length=200)),
                ('short_description_ar', models.CharField(blank=True, max_length=200)),
                ('icon', models.CharField(blank=True, help_text="Icon name from icon library (e.g., 'home')", max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_unit', models.CharField(blank=True, help_text="e.g., 'per hour', 'per sq ft', etc.", max_length=50)),
                ('duration', models.CharField(blank=True, help_text="e.g., '2-3 weeks'", max_length=50)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of appearance in listing')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='services.servicecategory')),
            ],
            options={
                'ordering': ['order', 'title_en'],
            },
        ),
        migrations.CreateModel(
            name='ServiceFeature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_en', models.CharField(max_length=200)),
                ('name_ar', models.CharField(blank=True, max_length=200)),
                ('description_en', models.TextField(blank=True)),
                ('description_ar', models.TextField(blank=True)),
                ('is_included', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='services.service')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
