# Generated by Django 5.1.6 on 2025-04-12 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Cover image displayed at the top of the service page', null=True, upload_to='services/covers/'),
        ),
    ]
