# Generated by Django 5.1.6 on 2025-04-12 15:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_footersection_footersettings_newslettersubscription_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterAutomation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('trigger_type', models.CharField(choices=[('subscription', 'New Subscription'), ('confirmation', 'Email Confirmed'), ('segment_added', 'Added to Segment'), ('time_delay', 'Time Delay')], max_length=20)),
                ('delay_days', models.PositiveIntegerField(default=0, help_text='Days to wait before sending (for time_delay trigger)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Newsletter Automation',
                'verbose_name_plural': 'Newsletter Automations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterCampaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('sending', 'Sending'), ('sent', 'Sent'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_recipients', models.PositiveIntegerField(default=0)),
                ('successful_deliveries', models.PositiveIntegerField(default=0)),
                ('opens', models.PositiveIntegerField(default=0)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('bounces', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Newsletter Campaign',
                'verbose_name_plural': 'Newsletter Campaigns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('welcome', 'Welcome Email'), ('confirmation', 'Confirmation Email'), ('newsletter', 'Regular Newsletter'), ('announcement', 'Announcement'), ('promotional', 'Promotional'), ('digest', 'Weekly/Monthly Digest'), ('event', 'Event Invitation'), ('custom', 'Custom')], max_length=20)),
                ('subject_en', models.CharField(max_length=200, verbose_name='Subject (English)')),
                ('subject_ar', models.CharField(blank=True, max_length=200, verbose_name='Subject (Arabic)')),
                ('content_en', models.TextField(verbose_name='Content (English)')),
                ('content_ar', models.TextField(blank=True, verbose_name='Content (Arabic)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Newsletter Template',
                'verbose_name_plural': 'Newsletter Templates',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriberSegment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Subscriber Segment',
                'verbose_name_plural': 'Subscriber Segments',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='newslettersubscription',
            name='confirmation_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='newslettersubscription',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='newslettersubscription',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='newslettersubscription',
            name='language_preference',
            field=models.CharField(choices=[('en', 'English'), ('ar', 'Arabic')], default='en', max_length=2),
        ),
        migrations.AddField(
            model_name='newslettersubscription',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='EmailDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('opened', 'Opened'), ('clicked', 'Clicked'), ('bounced', 'Bounced'), ('failed', 'Failed'), ('unsubscribed', 'Unsubscribed')], default='pending', max_length=20)),
                ('tracking_key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
                ('open_count', models.PositiveIntegerField(default=0)),
                ('click_count', models.PositiveIntegerField(default=0)),
                ('bounce_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_emails', to='contact.newslettersubscription')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='contact.newslettercampaign')),
            ],
            options={
                'verbose_name': 'Email Delivery',
                'verbose_name_plural': 'Email Deliveries',
                'ordering': ['-created_at'],
                'unique_together': {('campaign', 'subscriber')},
            },
        ),
        migrations.CreateModel(
            name='LinkClick',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('clicked_at', models.DateTimeField(auto_now_add=True)),
                ('user_agent', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_clicks', to='contact.emaildelivery')),
            ],
            options={
                'verbose_name': 'Link Click',
                'verbose_name_plural': 'Link Clicks',
                'ordering': ['-clicked_at'],
            },
        ),
        migrations.CreateModel(
            name='AutomationStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('delay_days', models.PositiveIntegerField(default=0, help_text='Days to wait before sending this step after the previous one')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('automation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='contact.newsletterautomation')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='automation_steps', to='contact.newslettertemplate')),
            ],
            options={
                'verbose_name': 'Automation Step',
                'verbose_name_plural': 'Automation Steps',
                'ordering': ['automation', 'order'],
                'unique_together': {('automation', 'order')},
            },
        ),
        migrations.AddField(
            model_name='newslettercampaign',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='contact.newslettertemplate'),
        ),
        migrations.AddField(
            model_name='newslettercampaign',
            name='segments',
            field=models.ManyToManyField(blank=True, related_name='campaigns', to='contact.subscribersegment'),
        ),
        migrations.AddField(
            model_name='newsletterautomation',
            name='segment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automations', to='contact.subscribersegment'),
        ),
        migrations.CreateModel(
            name='AutomationExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('next_step_scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_executions', to='contact.newslettersubscription')),
                ('current_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executions', to='contact.automationstep')),
                ('automation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='contact.newsletterautomation')),
            ],
            options={
                'verbose_name': 'Automation Execution',
                'verbose_name_plural': 'Automation Executions',
                'ordering': ['-started_at'],
                'unique_together': {('automation', 'subscriber')},
            },
        ),
        migrations.CreateModel(
            name='SubscriberSegmentMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='contact.subscribersegment')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segment_memberships', to='contact.newslettersubscription')),
            ],
            options={
                'verbose_name': 'Segment Membership',
                'verbose_name_plural': 'Segment Memberships',
                'unique_together': {('subscriber', 'segment')},
            },
        ),
    ]
