# Generated by Django 5.1.6 on 2025-04-26 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('subtitle', models.CharField(max_length=500, verbose_name='Subtitle')),
                ('mission_title', models.CharField(max_length=200, verbose_name='Mission Title')),
                ('mission_description', models.TextField(verbose_name='Mission Description')),
                ('vision_title', models.CharField(max_length=200, verbose_name='Vision Title')),
                ('vision_description', models.TextField(verbose_name='Vision Description')),
                ('team_section_title', models.CharField(max_length=200, verbose_name='Team Section Title')),
                ('values_section_title', models.CharField(max_length=200, verbose_name='Values Section Title')),
                ('testimonials_section_title', models.CharField(max_length=200, verbose_name='Testimonials Section Title')),
                ('history_section_title', models.CharField(blank=True, max_length=200, verbose_name='History Section Title')),
                ('meta_description', models.TextField(blank=True, verbose_name='Meta Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title_ar', models.CharField(max_length=200, verbose_name='Title (Arabic)')),
                ('subtitle_ar', models.CharField(max_length=500, verbose_name='Subtitle (Arabic)')),
                ('mission_title_ar', models.CharField(max_length=200, verbose_name='Mission Title (Arabic)')),
                ('mission_description_ar', models.TextField(verbose_name='Mission Description (Arabic)')),
                ('vision_title_ar', models.CharField(max_length=200, verbose_name='Vision Title (Arabic)')),
                ('vision_description_ar', models.TextField(verbose_name='Vision Description (Arabic)')),
                ('team_section_title_ar', models.CharField(max_length=200, verbose_name='Team Section Title (Arabic)')),
                ('values_section_title_ar', models.CharField(max_length=200, verbose_name='Values Section Title (Arabic)')),
                ('testimonials_section_title_ar', models.CharField(max_length=200, verbose_name='Testimonials Section Title (Arabic)')),
                ('history_section_title_ar', models.CharField(blank=True, max_length=200, verbose_name='History Section Title (Arabic)')),
                ('meta_description_ar', models.TextField(blank=True, verbose_name='Meta Description (Arabic)')),
            ],
            options={
                'verbose_name': 'About Page Content',
                'verbose_name_plural': 'About Page Content',
            },
        ),
        migrations.CreateModel(
            name='ClientLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Client Name')),
                ('logo', models.ImageField(upload_to='clients/', verbose_name='Logo')),
                ('url', models.URLField(blank=True, verbose_name='Website URL')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('name_ar', models.CharField(max_length=100, verbose_name='Client Name (Arabic)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Client Logo',
                'verbose_name_plural': 'Client Logos',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CompanyHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='Year')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('title_ar', models.CharField(max_length=200, verbose_name='Title (Arabic)')),
                ('description_ar', models.TextField(verbose_name='Description (Arabic)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company History Event',
                'verbose_name_plural': 'Company History Events',
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='CompanyStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('value', models.PositiveIntegerField(verbose_name='Value')),
                ('unit', models.CharField(blank=True, max_length=20, verbose_name='Unit')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('title_ar', models.CharField(max_length=100, verbose_name='Title (Arabic)')),
                ('unit_ar', models.CharField(blank=True, max_length=20, verbose_name='Unit (Arabic)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company Statistic',
                'verbose_name_plural': 'Company Statistics',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CoreValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('icon', models.CharField(help_text='Icon name or identifier', max_length=50, verbose_name='Icon')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('title_ar', models.CharField(max_length=100, verbose_name='Title (Arabic)')),
                ('description_ar', models.TextField(verbose_name='Description (Arabic)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Core Value',
                'verbose_name_plural': 'Core Values',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('role', models.CharField(max_length=100, verbose_name='Role')),
                ('bio', models.TextField(verbose_name='Biography')),
                ('image', models.ImageField(upload_to='team/', verbose_name='Image')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('linkedin', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='Department')),
                ('name_ar', models.CharField(max_length=100, verbose_name='Name (Arabic)')),
                ('role_ar', models.CharField(max_length=100, verbose_name='Role (Arabic)')),
                ('bio_ar', models.TextField(verbose_name='Biography (Arabic)')),
                ('department_ar', models.CharField(blank=True, max_length=100, verbose_name='Department (Arabic)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100, verbose_name='Client Name')),
                ('quote', models.TextField(verbose_name='Quote')),
                ('project', models.CharField(blank=True, max_length=100, verbose_name='Project')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured')),
                ('client_name_ar', models.CharField(max_length=100, verbose_name='Client Name (Arabic)')),
                ('quote_ar', models.TextField(verbose_name='Quote (Arabic)')),
                ('project_ar', models.CharField(blank=True, max_length=100, verbose_name='Project (Arabic)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'ordering': ['-created_at'],
            },
        ),
    ]
