# Generated by Django 5.1.6 on 2025-04-27 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='company',
            field=models.CharField(blank=True, max_length=100, verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='company_ar',
            field=models.CharField(blank=True, max_length=100, verbose_name='Company (Arabic)'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='testimonials/', verbose_name='Client Image'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='industry',
            field=models.CharField(blank=True, max_length=100, verbose_name='Industry'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='industry_ar',
            field=models.CharField(blank=True, max_length=100, verbose_name='Industry (Arabic)'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Rating from 1-5', null=True, verbose_name='Rating'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='role',
            field=models.CharField(blank=True, max_length=100, verbose_name='Role/Position'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='role_ar',
            field=models.CharField(blank=True, max_length=100, verbose_name='Role/Position (Arabic)'),
        ),
    ]
