# Generated by Django 5.2 on 2025-04-10 13:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_name_en', models.CharField(max_length=100)),
                ('client_name_ar', models.CharField(blank=True, max_length=100)),
                ('quote_en', models.TextField()),
                ('quote_ar', models.TextField(blank=True)),
                ('project', models.CharField(blank=True, max_length=200)),
                ('approved', models.BooleanField(default=False, help_text='Only approved testimonials will be displayed on the website')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'ordering': ['-created_at'],
            },
        ),
    ]
