# Generated by Django 5.1.6 on 2025-04-23 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=100, verbose_name='Name (English)')),
                ('name_ar', models.CharField(blank=True, max_length=100, verbose_name='Name (Arabic)')),
                ('slug', models.SlugField(help_text='URL-friendly identifier', unique=True, verbose_name='Slug')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in which category is displayed', verbose_name='Display Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'FAQ Category',
                'verbose_name_plural': 'FAQ Categories',
                'ordering': ['order', 'name_en'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=255, verbose_name='Question')),
                ('answer_text', models.TextField(verbose_name='Answer')),
                ('language', models.CharField(choices=[('en', 'English'), ('ar', 'Arabic'), ('fr', 'French'), ('de', 'German')], default='en', max_length=10, verbose_name='Language')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in which question is displayed within its category', verbose_name='Display Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='faqs.faqcategory', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['category', 'order', 'created_at'],
                'indexes': [models.Index(fields=['language'], name='faqs_faq_languag_e784f2_idx'), models.Index(fields=['is_active'], name='faqs_faq_is_acti_575f3a_idx'), models.Index(fields=['category', 'order'], name='faqs_faq_categor_147ff0_idx')],
            },
        ),
    ]
