# Generated by Django 5.1.6 on 2025-04-13 18:17

from django.db import migrations

def no_op(apps, schema_editor):
    # No operation needed since the contact app is disabled
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('footer', '0001_initial'),
        # Removed dependency on contact app since it's disabled
    ]

    operations = [
        migrations.RunPython(no_op, no_op),
    ]
