# Generated by Django 5.1.6 on 2025-04-21 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footer', '0002_transfer_footer_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='footersettings',
            name='contact_title_ar',
            field=models.CharField(blank=True, help_text="Optional: Override 'اتصل بنا' title (Arabic)", max_length=100),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='contact_title_en',
            field=models.CharField(blank=True, help_text="Optional: Override 'Contact Us' title", max_length=100),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='newsletter_label_ar',
            field=models.CharField(blank=True, help_text="Optional: Override 'النشرة الإخبارية' section title (Arabic)", max_length=100),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='newsletter_label_en',
            field=models.CharField(blank=True, help_text="Optional: Override 'Newsletter' section title", max_length=100),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='newsletter_text_ar',
            field=models.CharField(blank=True, help_text='Text/prompt above the newsletter signup form (Arabic)', max_length=200),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='newsletter_text_en',
            field=models.CharField(blank=True, help_text='Text/prompt above the newsletter signup form', max_length=200),
        ),
    ]
