# Generated by Django 5.1.6 on 2025-04-21 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footer', '0003_footersettings_contact_title_ar_and_more'),
    ]

    operations = [
        # Add a title field to FooterSection as a copy of title_en for backwards compatibility
        migrations.AddField(
            model_name='footersection',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        # Add an is_active field to FooterSettings with a default of True
        migrations.AddField(
            model_name='footersettings',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        # Add Footerlink fields if needed
        migrations.AddField(
            model_name='footerlink',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        # Run a data migration to populate the title fields from the title_en fields
        migrations.RunSQL(
            sql="""
            UPDATE footer_footersection SET title = title_en;
            UPDATE footer_footerlink SET title = title_en;
            """,
            reverse_sql="""
            -- No reverse action needed since we're keeping both fields
            """
        ),
    ]
