# Generated by Django 5.1.6 on 2025-04-21 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footer', '0004_auto_20250422_0022'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='footerlink',
            options={'ordering': ['section', 'order', 'title'], 'verbose_name': 'Footer Link', 'verbose_name_plural': 'Footer Links'},
        ),
        migrations.AlterModelOptions(
            name='footersection',
            options={'ordering': ['order', 'title'], 'verbose_name': 'Footer Section', 'verbose_name_plural': 'Footer Sections'},
        ),
        migrations.AlterField(
            model_name='footerlink',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='footerlink',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Enable or disable this link in the footer', verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='footerlink',
            name='open_in_new_tab',
            field=models.BooleanField(default=False, help_text='If enabled, the link will open in a new browser tab/window', verbose_name='Open in New Tab'),
        ),
        migrations.AlterField(
            model_name='footerlink',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Links are displayed in ascending order (0 appears first) within each section', verbose_name='Display Order'),
        ),
        migrations.AlterField(
            model_name='footerlink',
            name='section',
            field=models.ForeignKey(help_text='The footer section this link belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='links', to='footer.footersection', verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='footerlink',
            name='title',
            field=models.CharField(blank=True, editable=False, help_text='Legacy field for backwards compatibility', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='footerlink',
            name='title_ar',
            field=models.CharField(help_text='Arabic translation of the link title', max_length=100, verbose_name='Link Title (Arabic)'),
        ),
        migrations.AlterField(
            model_name='footerlink',
            name='title_en',
            field=models.CharField(help_text='Text displayed for this link. Example: "About Us", "Services", "Contact"', max_length=100, verbose_name='Link Title (English)'),
        ),
        migrations.AlterField(
            model_name='footerlink',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='footerlink',
            name='url',
            field=models.CharField(help_text='URL for this link. Can be a relative path (e.g., "/about") or an absolute URL (e.g., "https://example.com"). For internal pages, use relative paths starting with "/" (e.g., "/services").', max_length=255, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='footersection',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='footersection',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Enable or disable this section in the footer', verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='footersection',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Sections are displayed in ascending order (0 appears first)', verbose_name='Display Order'),
        ),
        migrations.AlterField(
            model_name='footersection',
            name='slug',
            field=models.SlugField(help_text='Unique identifier used in URLs and templates. Auto-generated from title if left blank.', max_length=120, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='footersection',
            name='title',
            field=models.CharField(blank=True, editable=False, help_text='Legacy field for backwards compatibility', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='footersection',
            name='title_ar',
            field=models.CharField(help_text='Arabic translation of the section title', max_length=100, verbose_name='Title (Arabic)'),
        ),
        migrations.AlterField(
            model_name='footersection',
            name='title_en',
            field=models.CharField(help_text='Section heading displayed in the footer. Example: "Quick Links", "Services", "Information"', max_length=100, verbose_name='Title (English)'),
        ),
        migrations.AlterField(
            model_name='footersection',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='address_ar',
            field=models.TextField(help_text='Arabic translation of your company address', max_length=200, verbose_name='Address (Arabic)'),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='address_en',
            field=models.TextField(help_text='Example: "123 Design Street, Creative District, City"', max_length=200, verbose_name='Address (English)'),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='company_name_ar',
            field=models.CharField(help_text='Arabic translation of your company name', max_length=100, verbose_name='Company Name (Arabic)'),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='company_name_en',
            field=models.CharField(help_text='Example: "Archway Interior Design"', max_length=100, verbose_name='Company Name (English)'),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='contact_title_ar',
            field=models.CharField(blank=True, help_text='Arabic translation of your custom contact section title. Leave blank if the English field is blank.', max_length=100, null=True, verbose_name='Contact Section Title (Arabic)'),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='contact_title_en',
            field=models.CharField(blank=True, help_text='Override the default "Contact Us" title. Leave blank to use default. Example: "Get in Touch"', max_length=100, null=True, verbose_name='Contact Section Title (English)'),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='copyright_text_ar',
            field=models.CharField(help_text='Arabic translation of your copyright text', max_length=200, verbose_name='Copyright Text (Arabic)'),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='copyright_text_en',
            field=models.CharField(help_text='Example: "© 2023 Archway Interior Design. All rights reserved."', max_length=200, verbose_name='Copyright Text (English)'),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='description_ar',
            field=models.TextField(help_text='Arabic translation of your company description', max_length=500, verbose_name='Description (Arabic)'),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='description_en',
            field=models.TextField(help_text='A brief description of your company. Example: "Leading interior design studio specializing in modern and sustainable solutions."', max_length=500, verbose_name='Description (English)'),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='email',
            field=models.EmailField(help_text='Example: "contact@archway.com"', max_length=100, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Enable or disable the entire footer', verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='newsletter_label_ar',
            field=models.CharField(help_text='Arabic translation of your newsletter input label', max_length=100, verbose_name='Newsletter Input Label (Arabic)'),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='newsletter_label_en',
            field=models.CharField(help_text='Label for the newsletter input field. Example: "Enter your email"', max_length=100, verbose_name='Newsletter Input Label (English)'),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='newsletter_text_ar',
            field=models.CharField(help_text='Arabic translation of your newsletter text', max_length=200, verbose_name='Newsletter Text (Arabic)'),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='newsletter_text_en',
            field=models.CharField(help_text='Text displayed above the newsletter signup form. Example: "Subscribe to our newsletter for design tips and updates."', max_length=200, verbose_name='Newsletter Text (English)'),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='phone',
            field=models.CharField(help_text='Example: "+1 (555) 123-4567"', max_length=50, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='show_newsletter',
            field=models.BooleanField(default=True, help_text='Enable or disable the newsletter signup form in the footer', verbose_name='Show Newsletter Signup'),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='icon',
            field=models.CharField(blank=True, help_text='Optional: Font Awesome icon class to override the default icon. Leave blank to use default. Example: "fab fa-instagram"', max_length=100, null=True, verbose_name='Custom Icon Class'),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Enable or disable this social media link in the footer', verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Social media links are displayed in ascending order (0 appears first)', verbose_name='Display Order'),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='platform',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('twitter', 'Twitter'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('youtube', 'YouTube'), ('pinterest', 'Pinterest'), ('tiktok', 'TikTok'), ('whatsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('snapchat', 'Snapchat'), ('behance', 'Behance'), ('dribbble', 'Dribbble'), ('github', 'GitHub'), ('medium', 'Medium'), ('other', 'Other')], help_text='Select the social media platform', max_length=50, verbose_name='Platform'),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='url',
            field=models.URLField(help_text="Full URL to your social media profile. Example: 'https://www.instagram.com/your_profile'", max_length=255, verbose_name='URL'),
        ),
    ]
