# Generated by Django 5.1.6 on 2025-04-22 02:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footer', '0006_alter_footersettings_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterBottomLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title_en', models.CharField(help_text='Text displayed for this link. Example: "Terms of Service", "Privacy Policy"', max_length=100, verbose_name='Link Title (English)')),
                ('title_ar', models.CharField(help_text='Arabic translation of the link title', max_length=100, verbose_name='Link Title (Arabic)')),
                ('url', models.CharField(help_text='URL for this link. Can be a relative path (e.g., "/terms") or an absolute URL. For internal pages, use relative paths starting with "/" (e.g., "/privacy").', max_length=255, verbose_name='URL')),
                ('order', models.PositiveIntegerField(default=0, help_text='Links are displayed in ascending order (0 appears first)', verbose_name='Display Order')),
                ('is_active', models.BooleanField(default=True, help_text='Enable or disable this link in the footer', verbose_name='Active')),
                ('open_in_new_tab', models.BooleanField(default=False, help_text='If enabled, the link will open in a new browser tab/window', verbose_name='Open in New Tab')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Footer Bottom Link',
                'verbose_name_plural': 'Footer Bottom Links',
                'ordering': ['order', 'title_en'],
            },
        ),
    ]
